
name: sneaker_flutter
description: A new Flutter project with Serverpod.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  go_router:
  gap:
  rxdart:
  cached_network_image:
  shared_preferences:

  serverpod_flutter: 2.3.0

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_lints: '>=3.0.0 <6.0.0'
  flutter_test:
    sdk: flutter

dependency_overrides:
  sneaker_client:
    path: ../stepish_client


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

